// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// sim1
int sim1(IntegerVector x, List probs, int nSubjects, int startWeek);
RcppExport SEXP _RCTRecruit_sim1(SEXP xSEXP, SEXP probsSEXP, SEXP nSubjectsSEXP, SEXP startWeekSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< List >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< int >::type nSubjects(nSubjectsSEXP);
    Rcpp::traits::input_parameter< int >::type startWeek(startWeekSEXP);
    rcpp_result_gen = Rcpp::wrap(sim1(x, probs, nSubjects, startWeek));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RCTRecruit_sim1", (DL_FUNC) &_RCTRecruit_sim1, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_RCTRecruit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
