# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim1 <- function(x, probs, nSubjects, startWeek = 1L) {
    .Call(`_RCTRecruit_sim1`, x, probs, nSubjects, startWeek)
}

getPredVec <- function(x, probs) {
    .Call(`_RCTRecruit_getPredVec`, x, probs)
}

getDistance <- function(x, y, probs) {
    .Call(`_RCTRecruit_getDistance`, x, y, probs)
}

PredCIbyWk <- function(x, probs, nSim, pq) {
    .Call(`_RCTRecruit_PredCIbyWk`, x, probs, nSim, pq)
}

